### ISSUE TITLE
Feature request: Option to disable project name prefix for service names

### ISSUE THREAD

**Issue by petergombos** [ddrozdov/docker-compose-swarm-mode#24]
I'm having trouble with prefixed service names since I use them directly in my source code the way they are defined in my compose configuration. It would be awesome to have an option to disable it so it would behave the same way as in the official docker-compose.

Thanks!

**Comment by ddrozdov** [comment]
The official docker-compose adds the project name as a prefix for all the services in a compose file. That's exactly why I've done it like that in my script.
Do you mean there is some option to disable this in docker-compose?

**Comment by petergombos** [comment]
You are right, and I'm sorry that I didn't explain myself clear enough. My problem is that in docker-compose services are accessable to linked containers by their service name as DNS hostnames.

```
version: '2'
services:
  api:
    image: api
    links:
      - loadbalancer
  loadbalancer:
   ...
```

So in the example above, loadbalancer image can have hardcoded 'api' in it's config, since it will be accessable via the hostname. Problem is that when I use docker-compose-swarm-mode I can only access them by the hostname 'prefix_api' from my containers.

**Comment by ddrozdov** [comment]
Ok, I see now.
According to what I've read, this has been done in docker-compose by creating an additional "internal" network for a docker-compose file and registering all the services in that network by their names.
I don't think it's possible to implement the same technique with `docker service`.

What I can do is support an empty string as a project name that would disable prefixing for containers, volumes, and networks.
But, as for me, in your case I'd pass the correct hostname of `api` to `loadbalancer` as an environment property or mount a correct config file if env isn't supported by `loadbalancer`, because without prefixes you won't be able to use the same service names in other docker-compose.yml files.

**Comment by petergombos** [comment]
The empty string could work for me. I do understand that your suggested approach would be better (using envs) I'll look into it, problem with Nginx is that it doesn't support environment variables out of the box.

**Comment by ddrozdov** [comment]
You can now run the script like this to get rid of any prefixes:
`docker-compose-swarm-mode -p "" ...`

**Comment by petergombos** [comment]
Great, thanks!  Awesome work on this script by the way, very useful little tool!
